# Generated by Django 5.0.1 on 2024-01-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('city', models.CharField(default=False, max_length=100)),
                ('gender', models.CharField(default=True, max_length=100)),
                ('SSC', models.BooleanField(default=False)),
                ('HSC', models.BooleanField(default=False)),
                ('graduate', models.BooleanField(default=False)),
            ],
        ),
    ]
